name: Angular CICD
on:
  push:
    branches:
      - "develop"
  pull_request:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Descargar dependencias y ejecutar pruebas"
        run: |
          npm ci
          npm test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ejecutando sonar"

  build:
    runs-on: ubuntu-latest
    needs: [tests,sonarcloud]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Descargar dependencias y compilar"
        run: |
          npm ci
          npm run build
          ls
  

  
    